about_widget_content = "La tecnologia anche per neofiti."
address = "Corso G.Matteotti 40 Castellanza 21053 (VA)"
author = "Licci Dario"
contact_form_action = "netlify"
copyright = "Designed By [Licci Dario](https://liccidario.com/) & Developed By [Licci Dario](https://liccidario.com/)"
custom_script = ""
description = "This is meta description"
email = "info@liccidario.com"
favicon = "images/favicon.png"
featured_post_title = "Post in primo piano"
footer_content = "La tecnologia anche per neofiti."
image = "images/logo.png"
logo = "images/logo.webp"
logo_text = "Boilerplate"
logo_width = "150x"
mainSections = ["blog"]
mobile = "329-18-63-012"
navbar_fixed = false
recent_post_title = "Post Recenti"
search = true
[advertisement]
image = "images/promotion.png"
link = "https://liccidario.com/negozio"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Scopri di più"
button_link = "about/"
content = "Ciao sono Dario, aiuto Aziende e Privati nel mondo dell'informatica."
enable = true
image = "images/banner.png"
title_large = "Niente Stress, Velocità, Prezzi Onesti **!**"
title_small = "Fatti conigliare dai Professionisti "
[cookies]
button = " Accetto"
content = "Questo sito utilizza i cookie. Continuando a utilizzare questo sito Web, acconsenti al loro utilizzo."
enable = true
expire_days = 2
[preloader]
enable = true
preloader = ""
[subscription]
enable = false
mailchimp_form_action = "https://app.us14.list-manage.com/subscribe/post?u=bc0c9b25d45bb944b76d9b6bb&amp;id=5f133e0cdc"
mailchimp_form_name = "mc-embedded-subscribe-form"
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/liccidario"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/liccidario_com"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/pc_gaming_castellanza"
title = "instagram"
[[social]]
icon = "fab fa-github"
link = "#"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/dario-licci/"
title = "linkedin"
